# Generated by Django 5.2.1 on 2025-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image_alter_category_title_alter_location_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                null=True,
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
